# Generated by Django 5.2.2 on 2025-06-19 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uploader_id', models.BigIntegerField(verbose_name='上传用户ID')),
                ('channel_id', models.BigIntegerField(verbose_name='所属频道ID')),
                ('file', models.FileField(upload_to='chat_files/', verbose_name='文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.PositiveIntegerField(help_text='单位：字节', verbose_name='文件大小')),
                ('content_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME类型')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('is_temp', models.BooleanField(default=False, verbose_name='是否为临时文件')),
            ],
            options={
                'verbose_name': '聊天文件',
                'verbose_name_plural': '聊天文件记录',
                'db_table': 'chat_file',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['uploader_id'], name='chat_file_uploade_e3dbea_idx'), models.Index(fields=['channel_id'], name='chat_file_channel_db810b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True, verbose_name='消息内容')),
                ('file_id', models.BigIntegerField(blank=True, null=True, verbose_name='文件ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('channel', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='channel.channel', verbose_name='频道')),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息管理',
                'db_table': 'chat_message',
                'ordering': ['timestamp'],
            },
        ),
    ]
